### ISSUE TITLE
The time has come - WithSix is RIP

### ISSUE THREAD

**Issue by Avil** [Dahlgren/arma-server-web-admin#105]
Repro steps: read https://medium.com/withsix/farewell-2f0257e7aab7 

Guess it's time to make the steam-workshop branch live or mothball the project. :(

Thanks for all your work on this.

**Comment by ToasterBR** [comment]
Well, we have been using that branch since the early days and everything works smoothly. 

Sad about WithSix but to be honest, your work @Dahlgren and Steam Workshop removed a lot of hassle we used to have with mod management and server creation.

I think would be nice to focus on Steam but this is just my 2 cents.

**Comment by Dahlgren** [comment]
I've been doing a bit of skunk work for a potential different way of integrating Steam. It would remove the need for account details and gives proper downloading progress and update status, both for Steam Workshop and game updates.

**Comment by ToasterBR** [comment]
Looks great. If you need testing just let me know!

**Comment by shadez95** [comment]
I really want to use this but since withSIX is dead (site is still up though) I'm afraid to get it up and running and then not be able to get mods to work right with it since it uses withSIX for mods.

**Comment by Dahlgren** [comment]
withSIX is only used to download or update mods. Added mods which are not fetched from withSIX are not managed. Running servers with mods does not invoke withSIX.

**Comment by Dahlgren** [comment]
withSIX removed since it caused startup crashes
