### ISSUE TITLE
Wrong CBA in mods

### ISSUE THREAD

**Issue by Marco674** [Dahlgren/arma-server-web-admin#33]
Hi,

When i select mods i have automatically CBA added to the mod list, 
But this is not my version, 
![capture d ecran 2017-02-21 a 08 49 02](https://cloud.githubusercontent.com/assets/23456998/23155458/f2baad2a-f812-11e6-8e3c-5ab2120380cd.png)
See cba cba_co and cba_a3 at the end

**Comment by Dahlgren** [comment]
It will try to automatically figure out any mod dependencies based on what mods are currently selected based on data available from Play withSIX.

The duplicate `@cba_a3` is probably due to bug with bad comparison since your `@CBA_A3` is in uppercase and should be fixed.

The old `@cba` and `@cba_co` is due to `@ace` listing them as dependencies on Play withSIX. If the mod name is `@ace3` instead it will calculate the dependencies for Arma 3 instead as `@cba_a3`. The Play withSIX integration should probably be optional and configurable in the config or so. At least if the mods are not listed as installed from Play withSIX. It's the same handling as for installing mods from Play withSIX and their dependencies.

**Comment by Marco674** [comment]
Ok thank you,
Good luck :)

**Comment by Dahlgren** [comment]
The game will ignore any nonexisting mods but if you want to avoid the `@cba` and `@cba_co` you could rename your `@ace` to `@ace3` for now. I'll try to fix the bug with the duplicated `@cba_a3` asap.

I'll probably create a separate ticket for making Play withSIX integration optional since it's a bigger overall issue for the manager. With Steam Workshop integration it probably won't be that interesting to use other than for legacy mods either :)

**Comment by flexgrip** [comment]
Yes, I would love to change some config and not have anything to do with play with six. Once we get workshop support for mods, play with six is irrelevant anyway.

Great work!

**Comment by Dahlgren** [comment]
I've created a branch where Play withSIX is removed from almost all the app. Now I just need to add it again where needed for those who use it. Some frontend UI elements such as removing mod search are yet to be fixed too.

**Comment by Marco674** [comment]
Nice, already tested, and works great.

**Comment by Dahlgren** [comment]
Cool, thanks for testing 😃 

I created a couple of OFP and Arma 1 servers last week and all the Play withSIX stuff was just an annoyance so that motivated me to fix it ASAP
